### PR TITLE
MongoDB transport base

### PR DESCRIPTION
**Pull request by clairekuang**
Closes specklesystems/Core#12

### CODE REVIEW

**Comment by didimitrie** [comment]
Hi @clairekuang! Thanks for this PR. One thing that I'm worried about is that I see no dependencies to the [mongodb driver](https://www.nuget.org/packages/mongocsharpdriver) added to the csproj file, maybe that was missed in the `git add` step?

**Comment by clairekuang** [comment]
@didimitrie  forgot to commit .csproj updates! The mongo package reference should be included now

**Comment by didimitrie** [comment]
Just passing by to say that we're not merging this *yet* as we've uncovered a little structural problem of having all the transports inside Core proper: we'll end up having a wee bit too many dependencies! 

We're thinking of a way to do organise this to be future proof, and hopefully we'll be able to proceed! (PS: i've started tracking this issue in #36).

**Comment by izzylys** [comment]
Thanks a lot for this PR Claire ✨

As Dimitrie mentioned, we've decided to move transports out of Core to prevent bloating of Core itself as more transports are added over time. We've just merged this change (along with your MongoDB transport) in #38 

Closing this PR as the changes have already been merged into master 🚀

**Pull request closed without merging**
